//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPINT_GRUPO_21_PR3.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPINT_GRUPO_21_PR3.App_GlobalResources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Patient.
        /// </summary>
        internal static string btnAddPatient {
            get {
                return ResourceManager.GetString("btnAddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Patient.
        /// </summary>
        internal static string btnCargarPaciente {
            get {
                return ResourceManager.GetString("btnCargarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClearSearch {
            get {
                return ResourceManager.GetString("btnClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnConfirmDelete {
            get {
                return ResourceManager.GetString("btnConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Patient.
        /// </summary>
        internal static string btnCreatePatient {
            get {
                return ResourceManager.GetString("btnCreatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEditar {
            get {
                return ResourceManager.GetString("btnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string btnGenerate {
            get {
                return ResourceManager.GetString("btnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string btnLoguearse {
            get {
                return ResourceManager.GetString("btnLoguearse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        internal static string btnNewAppointment {
            get {
                return ResourceManager.GetString("btnNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Doctor.
        /// </summary>
        internal static string btnNewDoctor {
            get {
                return ResourceManager.GetString("btnNewDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Patient.
        /// </summary>
        internal static string btnUpdatePatient {
            get {
                return ResourceManager.GetString("btnUpdatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Patients.
        /// </summary>
        internal static string cardBuscarPacientes {
            get {
                return ResourceManager.GetString("cardBuscarPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor List.
        /// </summary>
        internal static string cardDoctorList {
            get {
                return ResourceManager.GetString("cardDoctorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Interval Report.
        /// </summary>
        internal static string cardIntervalo {
            get {
                return ResourceManager.GetString("cardIntervalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient List.
        /// </summary>
        internal static string cardListadoPacientes {
            get {
                return ResourceManager.GetString("cardListadoPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Productivity Report.
        /// </summary>
        internal static string cardProductividad {
            get {
                return ResourceManager.GetString("cardProductividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Doctors.
        /// </summary>
        internal static string cardSearchDoctors {
            get {
                return ResourceManager.GetString("cardSearchDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string headerAddress {
            get {
                return ResourceManager.GetString("headerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Patient.
        /// </summary>
        internal static string headerAgregarPaciente {
            get {
                return ResourceManager.GetString("headerAgregarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment List.
        /// </summary>
        internal static string headerAppointmentList {
            get {
                return ResourceManager.GetString("headerAppointmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of appointments.
        /// </summary>
        internal static string headerAppointments {
            get {
                return ResourceManager.GetString("headerAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string headerBirthDate {
            get {
                return ResourceManager.GetString("headerBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string headerDate {
            get {
                return ResourceManager.GetString("headerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string headerDoctor {
            get {
                return ResourceManager.GetString("headerDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string headerEmail {
            get {
                return ResourceManager.GetString("headerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string headerEmployeeId {
            get {
                return ResourceManager.GetString("headerEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Time.
        /// </summary>
        internal static string headerEndingTime {
            get {
                return ResourceManager.GetString("headerEndingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string headerLocality {
            get {
                return ResourceManager.GetString("headerLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string headerName {
            get {
                return ResourceManager.GetString("headerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string headerNationality {
            get {
                return ResourceManager.GetString("headerNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string headerObservation {
            get {
                return ResourceManager.GetString("headerObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string headerPassword {
            get {
                return ResourceManager.GetString("headerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string headerPatient {
            get {
                return ResourceManager.GetString("headerPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string headerPhone {
            get {
                return ResourceManager.GetString("headerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string headerProvince {
            get {
                return ResourceManager.GetString("headerProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Appointments.
        /// </summary>
        internal static string headerSearchAppointments {
            get {
                return ResourceManager.GetString("headerSearchAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string headerSex {
            get {
                return ResourceManager.GetString("headerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        internal static string headerSpecialty {
            get {
                return ResourceManager.GetString("headerSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Time.
        /// </summary>
        internal static string headerStartingTime {
            get {
                return ResourceManager.GetString("headerStartingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string headerStatus {
            get {
                return ResourceManager.GetString("headerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string headerSurname {
            get {
                return ResourceManager.GetString("headerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string headerTime {
            get {
                return ResourceManager.GetString("headerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string headerUser {
            get {
                return ResourceManager.GetString("headerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lblApellido {
            get {
                return ResourceManager.GetString("lblApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (DNI, name or surname).
        /// </summary>
        internal static string lblBusqueda {
            get {
                return ResourceManager.GetString("lblBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        internal static string lblDNI {
            get {
                return ResourceManager.GetString("lblDNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string lblEmployeeId {
            get {
                return ResourceManager.GetString("lblEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string lblFechaFin {
            get {
                return ResourceManager.GetString("lblFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lblFechaInicio {
            get {
                return ResourceManager.GetString("lblFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string lblFechaNac {
            get {
                return ResourceManager.GetString("lblFechaNac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string lblLocalidad {
            get {
                return ResourceManager.GetString("lblLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string lblNacionalidad {
            get {
                return ResourceManager.GetString("lblNacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string lblPatient {
            get {
                return ResourceManager.GetString("lblPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string lblProvincia {
            get {
                return ResourceManager.GetString("lblProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (by name or surname).
        /// </summary>
        internal static string lblSearchDoctors {
            get {
                return ResourceManager.GetString("lblSearchDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string lblSexo {
            get {
                return ResourceManager.GetString("lblSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        internal static string lblSpecialty {
            get {
                return ResourceManager.GetString("lblSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        internal static string lblWelcomePlaceholder {
            get {
                return ResourceManager.GetString("lblWelcomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string navInformes {
            get {
                return ResourceManager.GetString("navInformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Doctors.
        /// </summary>
        internal static string navMedicos {
            get {
                return ResourceManager.GetString("navMedicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Patients.
        /// </summary>
        internal static string navPacientes {
            get {
                return ResourceManager.GetString("navPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Appointments.
        /// </summary>
        internal static string navTurnos {
            get {
                return ResourceManager.GetString("navTurnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Patient.
        /// </summary>
        internal static string titleAddPatient {
            get {
                return ResourceManager.GetString("titleAddPatient", resourceCulture);
            }
        }
    }
}
